apiVersion: v1
kind: Service
metadata:
  name: bar-service
  namespace: http-echo
spec:
  type: NodePort
  selector:
    app: bar
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30012